spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: "test.gumbo@gmail"
    password: "pjrnmlqplqgrpfez"
    protocol: smtp
    properties:
      mail:
        smtp:
          starttls:
            enable: true