spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/nok-project?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 1234

  jpa:
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
    hibernate:
      ddl-auto: create

  mail:
    host: smtp.mailgun.org
    port: 587
    protocol: smtp
    properties:
      mail:
        smtp:
          starttls:
            enable: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

front:
  url: http://localhost:3000

app:
  firebase-configuration-file: config/nok-storage-firebase-key.json
  firebase-bucket: nok-storage.appspot.com