on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: [ self-hosted ]

    steps:
    - name: Docker run
      working-directory: /home/ubuntu/kb-jobtraining/frontend
      run: |
        ls
        git pull
        npm run build
        pm2 stop index && pm2 delete index && pm2 start build/index.js
